#!/usr/bin/env python3
"""
Emit the two JS data files the dashboard reads, from the resolved data:
  - js/wells-data.js          const WELLS = [ {well_name, site_code, ...}, ... ]
  - js/measurements-data.js   const MEASUREMENTS = { site_code: [ {d,gwe,dtw,qa} ] }
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DATA = ROOT / "data"
JS = ROOT / "js"
JS.mkdir(exist_ok=True)


def main() -> None:
    wells = json.loads((DATA / "wells_resolved.json").read_text())
    out_wells = []
    for w in wells:
        out_wells.append({
            "well_name": w["well_id"],
            "swn": w.get("swn"),
            "site_code": w.get("site_code"),
            "mgmt_area": w.get("zone"),
            "latitude": w.get("latitude"),
            "longitude": w.get("longitude"),
            "well_use": w.get("well_use"),
            "well_depth": w.get("well_depth"),
            "gse": w.get("gse"),
            "rpe": w.get("rpe"),
            "top_perf": w.get("top_perf"),
            "bottom_perf": w.get("bottom_perf"),
            "principal_aquifer": w.get("principal_aquifer"),
            "county": w.get("county"),
            "gsa": w.get("gsa"),
            "mt_ft": w.get("mt_ft"),
            "mo_ft": w.get("mo_ft"),
        })
    (JS / "wells-data.js").write_text(
        "// Auto-generated by scripts/build_js.py - do not edit by hand.\n"
        "// Source: data/wells_resolved.json (Colusa_Yolo_RMS.xlsx, filtered to SCNY).\n\n"
        "const WELLS = " + json.dumps(out_wells) + ";\n")

    meas = json.loads((DATA / "measurements.json").read_text())
    meta = json.loads((DATA / "measurements_meta.json").read_text())
    (JS / "measurements-data.js").write_text(
        "// Auto-generated by scripts/build_js.py - do not edit by hand.\n"
        "// Source: DWR CKAN periodic GWL (data/measurements.json).\n\n"
        "const MEASUREMENTS_META = " + json.dumps(meta) + ";\n"
        "const MEASUREMENTS = " + json.dumps(meas) + ";\n")

    print(f"Wrote js/wells-data.js ({len(out_wells)} wells)")
    print(f"Wrote js/measurements-data.js ({meta['n_records']:,} records, "
          f"{meta['n_wells']} wells)")


if __name__ == "__main__":
    main()
